replicaCount: 1

image:
  repository: outlinewiki/outline
  pullPolicy: IfNotPresent
  tag: "version-0.54.0"     # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
  # - name: ""

env:
  SECRET_KEY: "0c56bbacc93edc61856559d5d99a2199fbde8ed3e9ed5ff71d4eb7fdef28ed58"
  UTILS_SECRET: "0c56bbacc93edc61856559d5d99a2199fbde8ed3e9ed5ff71d4eb7fdef28ed58"
  DATABASE_URL: "postgres://user:pass@localhost:5532/outline"
  DATABASE_URL_TEST: ""
  PGSSLMODE: "disable"
  REDIS_URL: "redis://:pass@localhost:6479"
  URL: "http://localhost:3000"
  PORT: "3000"
  SLACK_KEY: ""  # get_a_key_from_slack
  SLACK_SECRET: ""  # get_the_secret_of_above_key
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""

  # OPTIONAL
  CDN_URL: ""
  FORCE_HTTPS: "false"
  ENABLE_UPDATES: "true"
  DEBUG: "cache,presenters,events,emails,mailer,utils,multiplayer,server,services"
  ALLOWED_DOMAINS: ""
  SLACK_VERIFICATION_TOKEN: ""  # your_token
  SLACK_APP_ID: ""  # A0XXXXXXX
  SLACK_MESSAGE_ACTIONS: ""  # true
  GOOGLE_ANALYTICS_ID: ""
  SENTRY_DSN: ""
  AWS_ACCESS_KEY_ID: ""  # get_a_key_from_aws
  AWS_SECRET_ACCESS_KEY: ""  # get_the_secret_of_above_key
  AWS_REGION: ""  # xx-xxxx-x
  AWS_S3_UPLOAD_BUCKET_URL: ""  # http://s3:4569
  AWS_S3_UPLOAD_BUCKET_NAME: ""  # bucket_name_here
  AWS_S3_UPLOAD_MAX_SIZE: ""  # 26214400
  AWS_S3_FORCE_PATH_STYLE: ""  # true
  AWS_S3_ACL: ""  # private
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_FROM_EMAIL: ""
  SMTP_REPLY_EMAIL: ""
  DEFAULT_LANGUAGE: "en_US"
  
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: outline.example.com
      paths: []
  tls: []

resources:
  # limits:
  #   cpu: 1400m
  #   memory: 1512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
